language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-head
jdk:
  - openjdk7
gemfile: server/Gemfile
install:
  - cd server
  - bundle install
  - bin/deltacloud-db-upgrade
  - cd ../client
  - bundle install
  - cd ..
script:
  - cd server
  - bundle exec rake test
  - cd ../client
  - bundle exec rake test
notifications:
  email:
    - mi@mifo.sk
    - marios@redhat.com
    - lutter@redhat.com
    - rlandy@redhat.com
  irc:
    channels:
      - "irc.freenode.org#deltacloud"
    use_notice: true
    skip_join: false

