--- 
:gogrid: 
  :name: Gogrid
:mock: 
  :name: Mock
:rhevm: 
  :name: RHEVM
  :entrypoints:
    default:
      default: "https://rhev-m.localhost:8443/rhevm-api-powershell"
:rimuhosting: 
  :name: RimuHosting
:opennebula: 
  :class: OpennebulaDriver
  :name: Opennebula
:sbc: 
  :name: SBC
:terremark: 
  :name: Terremark
:rackspace: 
  :name: Rackspace
:azure: 
  :name: Azure
:eucalyptus:
  :name: Eucalyptus
  :username: Access Key ID
  :password: Secret Access Key
  :entrypoints:
    default:
      default: "ec2=EUCALYPTUS_IP[:PORT];s3=WALRUS_IP[:PORT]"
:ec2: 
  :entrypoints: 
    s3: 
      us-west-1: s3-us-west-1.amazonaws.com
      ap-southeast-1: s3-ap-southeast-1.amazonaws.com
      eu-west-1: s3-eu-west-1.amazonaws.com
      us-east-1: s3.amazonaws.com
    elb: 
      us-west-1: elasticloadbalancing.us-west-1.amazonaws.com
      ap-southeast-1: elasticloadbalancing.ap-southeast-1.amazonaws.com
      eu-west-1: elasticloadbalancing.eu-west-1.amazonaws.com
      us-east-1: elasticloadbalancing.us-east-1.amazonaws.com
    ec2: 
      us-west-1: ec2.us-west-1.amazonaws.com
      ap-southeast-1: ec2.ap-southeast-1.amazonaws.com
      eu-west-1: ec2.eu-west-1.amazonaws.com
      us-east-1: ec2.us-east-1.amazonaws.com
  :name: EC2
